* Project 4 Sorting

* Due:Friday 4/14 7:00am (the day after the last day of Spring Break)

* Description

Start with the class code that implements the selection, merge, and
quick sorts.

Write a new version of quick sort, qsort2. It should have this
signature ~std::vector<int> qsort2(std::vector<int>, int low, int
high);~.

It should:

1. Use a reasonable pivot (as opposed to just list[0])
2. It should perform the sort *in place*, that is it should
   rearrange the elements in the vector around the pivot as opposed to
   copying to a new vector. It should then return itself.
3. When first calling, low should be 0 and high should be the last
   index in the input vector. In each recursive call, low and high
   should be modified to index in to the part of the vector you're
   recursively sorting.

Run some timing tests on data sets of different sizes and
configurations to compare the merge and quick sorts we wrote together
in class with your new sort. Also, run the C++ built in sort and
compare that as well (you'll have to look that one up).


Edit this file and add comments below indicating what you found when
you did your timing experiments. 

* Notes:

This assignment does not require doctest testing. It does, however
require a make file that compiles to an executable named *main*. You
can create a new Makefile or copy and modify one you've used in the past.


* Write your comments here:   
Initially, when I wrote my quick sort with the middle value as the pivot,
it was somehow slower than the selection sort. I realized my mistake was in
the partitioning, so after some more trial and error, I looked up how 
to correctly do it. I watched several videos and read articles explaining the 
partitioning algorithm since I couldnt understand it. 

I knew the quick sort would be fast but I was actually suprised at how much 
faster the merge sort was in my testing. When I tested for 500,000 items.
The merge sort ended up being the second fastest. It was faster than the quick sort
I created, but my quick sort was faster than quick sort from class. Overall,
the default quick sort was the fastest by far. When I tested with smaller sizes,
however, my sort was faster with than the merge sort and the quick sort from class. 
But once again the default sort was the fastest. 
